### ISSUE TITLE
Do not show blueman applet

### ISSUE THREAD

**Issue by tari01** [AyatanaIndicators/ayatana-indicator-bluetooth#12]
When the Settings menuitem opens blueman's settings on MATE, blueman also displays the blueman applet in the indicator. We should look into ways of preventing that.

**Comment by flexiondotorg** [comment]
I have overcome this issue in Ubuntu MATE by overriding `/etc/xdg/autostart/blueman.desktop` with `/usr/share/mate/autostart/blueman.desktop`

### /etc/xdg/autostart/blueman.desktop

Here's the contents of `/etc/xdg/autostart/blueman.desktop`

```
[Desktop Entry]
Name=Blueman Applet
Comment=Blueman Bluetooth Manager
Icon=blueman
Exec=blueman-applet
Terminal=false
Type=Application
Categories=
X-Ubuntu-Gettext-Domain=blueman
```

I take that file copy it to `/usr/share/mate/autostart/blueman.desktop` add one line:

```
NotShowIn=MATE;
```

That prevents `blueman-applet` being autostarted in MATE during session initialisation.

I have a package called `ubuntu-mate-default-settings` which now includes the modified `/usr/share/mate/autostart/blueman.desktop` to prevent `blueman-applet` from being loaded.

**Comment by flexiondotorg** [comment]
This is not a complete solution, however. When `blueman-manager` is launched (via ayatana-indicator-bluetooth), it invokes `blueman-applet`.

**Comment by tari01** [comment]
@flexiondotorg 

I've had this fixed in my head, but couldn't get round to confirming and sharing it: blueman-applet needs to autostart and run all the time - this solves #17.

Then we should address this issue by removing the AppIndicator from
`org.blueman.general plugin-list ['AppIndicator', 'KillSwitch']`

I repeat: untested - but works well in my mind.

**Comment by tari01** [comment]
@flexiondotorg 

I have passed this upstream: https://github.com/blueman-project/blueman/issues/1495 - unfortunately there is nothing we can do here, closing.
