### ISSUE TITLE
Hide bluetooth icon on hardware without bluetooth support

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-bluetooth#42]
Hide bluetooth icon on hardware without bluetooth support

@tari01: Please work on this as paid work.

**Comment by tari01** [comment]
> Hide bluetooth icon on hardware without bluetooth support
> 
> @tari01: Please work on this as paid work.

We have two issues with this:

1. Running system indicators cannot be hidden. It's how Gtk menus are designed. If we change the visibility of a menu item that represents an indicator, the parent GtkMenu container crashes. This kind of makes sense.
2. Some time ago we agreed that the standard behaviour for indicators should be to always show **something**, so we should know if they are running. Here are some changes that ensured indicator visibility and prevented crashes: https://github.com/AyatanaIndicators/ayatana-indicator-bluetooth/commit/85de6718e008d628b84595ff2ca9e1ec86b54eaa, https://github.com/AyatanaIndicators/ayatana-indicator-datetime/commit/24d102c12a1470726c1d5321a918825cd3d18527.

**Comment by sunweaver** [comment]
And... but... the power indicator also only appears if we have a battery in some device. And it is also running in the background while not showing an icon.

For indicators that provide interactions with devices that are not present on the system, there is really no need to show anything, imho.

We should reconsider the policy under "2." in your above post.

**Comment by sunweaver** [comment]
> And... but... the power indicator also only appears if we have a battery in some device. And it is also running in the background while not showing an icon.

This can be demonstated in a VM (no battery, no indicator shown, process active in the background)

**Comment by tari01** [comment]
Just checked how I hacked the power indicator. It actually **is** also always visible, however, it shows no icon when there is no device. I will try the same approach here.

**Comment by sunweaver** [comment]
Nice. Very cool. Thanks.
